// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDuQWSVWYL0jbJPmbtBqEref8vwFs44ERg',
    appId: '1:86324842947:web:f68a3f5389fbc51290ed76',
    messagingSenderId: '86324842947',
    projectId: 'globalgoals-15dc8',
    authDomain: 'globalgoals-15dc8.firebaseapp.com',
    storageBucket: 'globalgoals-15dc8.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDR_8QjWE-XgFxBtjvNbIVliIEOeEMbTXY',
    appId: '1:86324842947:android:c6f8be9be4f0facd90ed76',
    messagingSenderId: '86324842947',
    projectId: 'globalgoals-15dc8',
    storageBucket: 'globalgoals-15dc8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC7ZV-afuQ8dPP6y6uPwcpwU0rIoilwilM',
    appId: '1:86324842947:ios:5da2e36b9ba343e890ed76',
    messagingSenderId: '86324842947',
    projectId: 'globalgoals-15dc8',
    storageBucket: 'globalgoals-15dc8.appspot.com',
    iosBundleId: 'com.example.globalgoalsapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC7ZV-afuQ8dPP6y6uPwcpwU0rIoilwilM',
    appId: '1:86324842947:ios:5da2e36b9ba343e890ed76',
    messagingSenderId: '86324842947',
    projectId: 'globalgoals-15dc8',
    storageBucket: 'globalgoals-15dc8.appspot.com',
    iosBundleId: 'com.example.globalgoalsapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDuQWSVWYL0jbJPmbtBqEref8vwFs44ERg',
    appId: '1:86324842947:web:004b37422c0abbc990ed76',
    messagingSenderId: '86324842947',
    projectId: 'globalgoals-15dc8',
    authDomain: 'globalgoals-15dc8.firebaseapp.com',
    storageBucket: 'globalgoals-15dc8.appspot.com',
  );
}
